// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PortSafe.Data;

#nullable disable

namespace CondominioEntregas.API.Data.Migrations
{
    [DbContext(typeof(PortSafeContext))]
    [Migration("20251205161338_EntregaNumeroCasaNullable")]
    partial class EntregaNumeroCasaNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PortSafe.Models.Armario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UltimaAbertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UltimoFechamento")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Armarios");
                });

            modelBuilder.Entity("PortSafe.Models.Condominio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeDoCondominio")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Condominios");
                });

            modelBuilder.Entity("PortSafe.Models.Entrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArmariumId")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoEntrega")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataHoraRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataHoraRetirada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnderecoGerado")
                        .HasColumnType("text");

                    b.Property<bool>("MensagemEnviada")
                        .HasColumnType("boolean");

                    b.Property<string>("NomeDestinatario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroCasa")
                        .HasColumnType("text");

                    b.Property<string>("SenhaAcesso")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TelefoneWhatsApp")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArmariumId");

                    b.ToTable("Entregas");
                });

            modelBuilder.Entity("PortSafe.Models.Unidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CondominioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MoradorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CondominioId");

                    b.ToTable("Unidade");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("PortSafe.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CondominioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResetTokenExpiracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<int>("Tipo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PortSafe.Models.UnidadeApartamento", b =>
                {
                    b.HasBaseType("PortSafe.Models.Unidade");

                    b.Property<string>("NumeroApartamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Torre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("UnidadesApartamento", (string)null);
                });

            modelBuilder.Entity("PortSafe.Models.UnidadeCasa", b =>
                {
                    b.HasBaseType("PortSafe.Models.Unidade");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumeroCasa")
                        .HasColumnType("integer");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("UnidadesCasa", (string)null);
                });

            modelBuilder.Entity("PortSafe.Models.Morador", b =>
                {
                    b.HasBaseType("PortSafe.Models.Usuario");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Photo")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UnidadeId")
                        .HasColumnType("integer");

                    b.HasIndex("CondominioId");

                    b.HasIndex("UnidadeId")
                        .IsUnique();

                    b.ToTable("Usuarios", t =>
                        {
                            t.Property("Telefone")
                                .HasColumnName("Morador_Telefone");
                        });

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("PortSafe.Models.Porteiro", b =>
                {
                    b.HasBaseType("PortSafe.Models.Usuario");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("CondominioId");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("PortSafe.Models.Entrega", b =>
                {
                    b.HasOne("PortSafe.Models.Armario", "Armario")
                        .WithMany("Entregas")
                        .HasForeignKey("ArmariumId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Armario");
                });

            modelBuilder.Entity("PortSafe.Models.Unidade", b =>
                {
                    b.HasOne("PortSafe.Models.Condominio", "Condominio")
                        .WithMany()
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("PortSafe.Models.UnidadeApartamento", b =>
                {
                    b.HasOne("PortSafe.Models.Unidade", null)
                        .WithOne()
                        .HasForeignKey("PortSafe.Models.UnidadeApartamento", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortSafe.Models.UnidadeCasa", b =>
                {
                    b.HasOne("PortSafe.Models.Unidade", null)
                        .WithOne()
                        .HasForeignKey("PortSafe.Models.UnidadeCasa", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortSafe.Models.Morador", b =>
                {
                    b.HasOne("PortSafe.Models.Condominio", "Condominio")
                        .WithMany("Moradores")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortSafe.Models.Unidade", "Unidade")
                        .WithOne("Morador")
                        .HasForeignKey("PortSafe.Models.Morador", "UnidadeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Condominio");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("PortSafe.Models.Porteiro", b =>
                {
                    b.HasOne("PortSafe.Models.Condominio", "Condominio")
                        .WithMany("Porteiros")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("PortSafe.Models.Armario", b =>
                {
                    b.Navigation("Entregas");
                });

            modelBuilder.Entity("PortSafe.Models.Condominio", b =>
                {
                    b.Navigation("Moradores");

                    b.Navigation("Porteiros");
                });

            modelBuilder.Entity("PortSafe.Models.Unidade", b =>
                {
                    b.Navigation("Morador");
                });
#pragma warning restore 612, 618
        }
    }
}
