// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PortSafe.Data;

#nullable disable

namespace CondominioEntregas.API.Data.Migrations
{
    [DbContext(typeof(PortSafeContext))]
    [Migration("20251014190844_RemoveAttributesMorador")]
    partial class RemoveAttributesMorador
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PortSafe.Models.Armario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UltimaAbertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UltimoFechamento")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Armarios");
                });

            modelBuilder.Entity("PortSafe.Models.Condominio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("NomeDoCondominio")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Condominios");

                    b.HasDiscriminator().HasValue("Condominio");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PortSafe.Models.Entrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArmarioId")
                        .HasColumnType("integer");

                    b.Property<int?>("ArmariumId")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoEntrega")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataHoraRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataHoraRetirada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnderecoGerado")
                        .HasColumnType("text");

                    b.Property<bool>("MensagemEnviada")
                        .HasColumnType("boolean");

                    b.Property<string>("NomeDestinatario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroCasa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaAcesso")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TelefoneWhatsApp")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArmarioId");

                    b.ToTable("Entregas");
                });

            modelBuilder.Entity("PortSafe.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CondominioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CondominioId");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<int>("Tipo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PortSafe.Models.CondApartamento", b =>
                {
                    b.HasBaseType("PortSafe.Models.Condominio");

                    b.Property<string>("Bloco")
                        .HasColumnType("text");

                    b.Property<string>("NumeroApartamento")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("CondApartamento");
                });

            modelBuilder.Entity("PortSafe.Models.CondCasa", b =>
                {
                    b.HasBaseType("PortSafe.Models.Condominio");

                    b.Property<string>("CEP")
                        .HasColumnType("text");

                    b.Property<int>("NumeroCasa")
                        .HasColumnType("integer");

                    b.Property<string>("Rua")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("CondCasa");
                });

            modelBuilder.Entity("PortSafe.Models.Morador", b =>
                {
                    b.HasBaseType("PortSafe.Models.Usuario");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CondominioId1")
                        .HasColumnType("integer");

                    b.Property<string>("Photo")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("CondominioId1");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("PortSafe.Models.Porteiro", b =>
                {
                    b.HasBaseType("PortSafe.Models.Usuario");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("PortSafe.Models.Entrega", b =>
                {
                    b.HasOne("PortSafe.Models.Armario", "Armario")
                        .WithMany("Entregas")
                        .HasForeignKey("ArmarioId");

                    b.Navigation("Armario");
                });

            modelBuilder.Entity("PortSafe.Models.Usuario", b =>
                {
                    b.HasOne("PortSafe.Models.Condominio", "Condominio")
                        .WithMany()
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("PortSafe.Models.Morador", b =>
                {
                    b.HasOne("PortSafe.Models.Condominio", null)
                        .WithMany("Moradores")
                        .HasForeignKey("CondominioId1");
                });

            modelBuilder.Entity("PortSafe.Models.Armario", b =>
                {
                    b.Navigation("Entregas");
                });

            modelBuilder.Entity("PortSafe.Models.Condominio", b =>
                {
                    b.Navigation("Moradores");
                });
#pragma warning restore 612, 618
        }
    }
}
